// Mocks generated by Mockito 5.4.6 from annotations
// in myapp/test/mock_generator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:myapp/academic_year_model.dart' as _i13;
import 'package:myapp/attendance_model.dart' as _i11;
import 'package:myapp/book_model.dart' as _i19;
import 'package:myapp/borrow_record_model.dart' as _i18;
import 'package:myapp/class_model.dart' as _i8;
import 'package:myapp/database_helper.dart' as _i3;
import 'package:myapp/event_model.dart' as _i14;
import 'package:myapp/grade_model.dart' as _i10;
import 'package:myapp/leave_model.dart' as _i16;
import 'package:myapp/performance_evaluation_model.dart' as _i17;
import 'package:myapp/staff_model.dart' as _i15;
import 'package:myapp/student_model.dart' as _i6;
import 'package:myapp/subject_model.dart' as _i9;
import 'package:myapp/teacher_model.dart' as _i7;
import 'package:myapp/timetable_model.dart' as _i12;
import 'package:myapp/user_model.dart' as _i5;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i3.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i4.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i4.Future<_i2.Database>);

  @override
  _i4.Future<int> createUser(_i5.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [user]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<_i5.User?> getUserByUsername(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByUsername, [username]),
            returnValue: _i4.Future<_i5.User?>.value(),
          )
          as _i4.Future<_i5.User?>);

  @override
  _i4.Future<List<_i5.User>> getUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, []),
            returnValue: _i4.Future<List<_i5.User>>.value(<_i5.User>[]),
          )
          as _i4.Future<List<_i5.User>>);

  @override
  _i4.Future<_i5.User?> getUserById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [id]),
            returnValue: _i4.Future<_i5.User?>.value(),
          )
          as _i4.Future<_i5.User?>);

  @override
  _i4.Future<int> updateUser(_i5.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteUser(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> createStudent(_i6.Student? student) =>
      (super.noSuchMethod(
            Invocation.method(#createStudent, [student]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i6.Student>> getStudents() =>
      (super.noSuchMethod(
            Invocation.method(#getStudents, []),
            returnValue: _i4.Future<List<_i6.Student>>.value(<_i6.Student>[]),
          )
          as _i4.Future<List<_i6.Student>>);

  @override
  _i4.Future<List<_i6.Student>> getStudentsByParentUserId(int? parentUserId) =>
      (super.noSuchMethod(
            Invocation.method(#getStudentsByParentUserId, [parentUserId]),
            returnValue: _i4.Future<List<_i6.Student>>.value(<_i6.Student>[]),
          )
          as _i4.Future<List<_i6.Student>>);

  @override
  _i4.Future<int> updateStudent(_i6.Student? student) =>
      (super.noSuchMethod(
            Invocation.method(#updateStudent, [student]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteStudent(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteStudent, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i6.Student>> searchStudents(
    String? nameQuery, {
    String? classId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchStudents,
              [nameQuery],
              {#classId: classId},
            ),
            returnValue: _i4.Future<List<_i6.Student>>.value(<_i6.Student>[]),
          )
          as _i4.Future<List<_i6.Student>>);

  @override
  _i4.Future<_i6.Student?> getStudentByEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#getStudentByEmail, [email]),
            returnValue: _i4.Future<_i6.Student?>.value(),
          )
          as _i4.Future<_i6.Student?>);

  @override
  _i4.Future<_i6.Student?> getStudentByUserId(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getStudentByUserId, [userId]),
            returnValue: _i4.Future<_i6.Student?>.value(),
          )
          as _i4.Future<_i6.Student?>);

  @override
  _i4.Future<int> createTeacher(_i7.Teacher? teacher) =>
      (super.noSuchMethod(
            Invocation.method(#createTeacher, [teacher]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i7.Teacher>> getTeachers() =>
      (super.noSuchMethod(
            Invocation.method(#getTeachers, []),
            returnValue: _i4.Future<List<_i7.Teacher>>.value(<_i7.Teacher>[]),
          )
          as _i4.Future<List<_i7.Teacher>>);

  @override
  _i4.Future<_i7.Teacher?> getTeacherByUserId(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTeacherByUserId, [userId]),
            returnValue: _i4.Future<_i7.Teacher?>.value(),
          )
          as _i4.Future<_i7.Teacher?>);

  @override
  _i4.Future<int> updateTeacher(_i7.Teacher? teacher) =>
      (super.noSuchMethod(
            Invocation.method(#updateTeacher, [teacher]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteTeacher(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTeacher, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i7.Teacher>> searchTeachers(
    String? name, {
    String? subject,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchTeachers, [name], {#subject: subject}),
            returnValue: _i4.Future<List<_i7.Teacher>>.value(<_i7.Teacher>[]),
          )
          as _i4.Future<List<_i7.Teacher>>);

  @override
  _i4.Future<int> createClass(_i8.SchoolClass? schoolClass) =>
      (super.noSuchMethod(
            Invocation.method(#createClass, [schoolClass]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i8.SchoolClass>> getClasses() =>
      (super.noSuchMethod(
            Invocation.method(#getClasses, []),
            returnValue: _i4.Future<List<_i8.SchoolClass>>.value(
              <_i8.SchoolClass>[],
            ),
          )
          as _i4.Future<List<_i8.SchoolClass>>);

  @override
  _i4.Future<_i8.SchoolClass?> getClassById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getClassById, [id]),
            returnValue: _i4.Future<_i8.SchoolClass?>.value(),
          )
          as _i4.Future<_i8.SchoolClass?>);

  @override
  _i4.Future<_i8.SchoolClass?> getClassByClassIdString(String? classId) =>
      (super.noSuchMethod(
            Invocation.method(#getClassByClassIdString, [classId]),
            returnValue: _i4.Future<_i8.SchoolClass?>.value(),
          )
          as _i4.Future<_i8.SchoolClass?>);

  @override
  _i4.Future<int> updateClass(_i8.SchoolClass? schoolClass) =>
      (super.noSuchMethod(
            Invocation.method(#updateClass, [schoolClass]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteClass(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteClass, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i8.SchoolClass>> searchClasses(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchClasses, [query]),
            returnValue: _i4.Future<List<_i8.SchoolClass>>.value(
              <_i8.SchoolClass>[],
            ),
          )
          as _i4.Future<List<_i8.SchoolClass>>);

  @override
  _i4.Future<int> createSubject(_i9.Subject? subject) =>
      (super.noSuchMethod(
            Invocation.method(#createSubject, [subject]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i9.Subject>> getSubjects() =>
      (super.noSuchMethod(
            Invocation.method(#getSubjects, []),
            returnValue: _i4.Future<List<_i9.Subject>>.value(<_i9.Subject>[]),
          )
          as _i4.Future<List<_i9.Subject>>);

  @override
  _i4.Future<_i9.Subject?> getSubjectById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSubjectById, [id]),
            returnValue: _i4.Future<_i9.Subject?>.value(),
          )
          as _i4.Future<_i9.Subject?>);

  @override
  _i4.Future<int> updateSubject(_i9.Subject? subject) =>
      (super.noSuchMethod(
            Invocation.method(#updateSubject, [subject]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteSubject(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSubject, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i9.Subject>> searchSubjects(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchSubjects, [query]),
            returnValue: _i4.Future<List<_i9.Subject>>.value(<_i9.Subject>[]),
          )
          as _i4.Future<List<_i9.Subject>>);

  @override
  _i4.Future<_i9.Subject?> getSubjectByName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#getSubjectByName, [name]),
            returnValue: _i4.Future<_i9.Subject?>.value(),
          )
          as _i4.Future<_i9.Subject?>);

  @override
  _i4.Future<_i9.Subject?> getSubjectBySubjectId(String? subjectId) =>
      (super.noSuchMethod(
            Invocation.method(#getSubjectBySubjectId, [subjectId]),
            returnValue: _i4.Future<_i9.Subject?>.value(),
          )
          as _i4.Future<_i9.Subject?>);

  @override
  _i4.Future<int> createGrade(_i10.Grade? grade) =>
      (super.noSuchMethod(
            Invocation.method(#createGrade, [grade]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i10.Grade>> getGrades() =>
      (super.noSuchMethod(
            Invocation.method(#getGrades, []),
            returnValue: _i4.Future<List<_i10.Grade>>.value(<_i10.Grade>[]),
          )
          as _i4.Future<List<_i10.Grade>>);

  @override
  _i4.Future<int> updateGrade(_i10.Grade? grade) =>
      (super.noSuchMethod(
            Invocation.method(#updateGrade, [grade]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteGrade(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGrade, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i10.Grade>> getGradesByStudent(int? studentId) =>
      (super.noSuchMethod(
            Invocation.method(#getGradesByStudent, [studentId]),
            returnValue: _i4.Future<List<_i10.Grade>>.value(<_i10.Grade>[]),
          )
          as _i4.Future<List<_i10.Grade>>);

  @override
  _i4.Future<List<_i10.Grade>> getGradesByClass(int? classId) =>
      (super.noSuchMethod(
            Invocation.method(#getGradesByClass, [classId]),
            returnValue: _i4.Future<List<_i10.Grade>>.value(<_i10.Grade>[]),
          )
          as _i4.Future<List<_i10.Grade>>);

  @override
  _i4.Future<List<_i10.Grade>> getGradesBySubject(int? subjectId) =>
      (super.noSuchMethod(
            Invocation.method(#getGradesBySubject, [subjectId]),
            returnValue: _i4.Future<List<_i10.Grade>>.value(<_i10.Grade>[]),
          )
          as _i4.Future<List<_i10.Grade>>);

  @override
  _i4.Future<List<_i10.Grade>> getGradesByClassAndSubject(
    int? classId,
    int? subjectId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGradesByClassAndSubject, [
              classId,
              subjectId,
            ]),
            returnValue: _i4.Future<List<_i10.Grade>>.value(<_i10.Grade>[]),
          )
          as _i4.Future<List<_i10.Grade>>);

  @override
  _i4.Future<void> upsertGrades(List<_i10.Grade>? grades) =>
      (super.noSuchMethod(
            Invocation.method(#upsertGrades, [grades]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAverageGradesBySubject() =>
      (super.noSuchMethod(
            Invocation.method(#getAverageGradesBySubject, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAverageGradesForClass(
    int? classId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAverageGradesForClass, [classId]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<int> createAttendance(_i11.Attendance? attendance) =>
      (super.noSuchMethod(
            Invocation.method(#createAttendance, [attendance]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i11.Attendance>> getAttendances() =>
      (super.noSuchMethod(
            Invocation.method(#getAttendances, []),
            returnValue: _i4.Future<List<_i11.Attendance>>.value(
              <_i11.Attendance>[],
            ),
          )
          as _i4.Future<List<_i11.Attendance>>);

  @override
  _i4.Future<int> updateAttendance(_i11.Attendance? attendance) =>
      (super.noSuchMethod(
            Invocation.method(#updateAttendance, [attendance]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteAttendance(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAttendance, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i11.Attendance>> getAttendancesByFilters({
    String? date,
    int? classId,
    int? subjectId,
    int? teacherId,
    int? studentId,
    int? lessonNumber,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAttendancesByFilters, [], {
              #date: date,
              #classId: classId,
              #subjectId: subjectId,
              #teacherId: teacherId,
              #studentId: studentId,
              #lessonNumber: lessonNumber,
            }),
            returnValue: _i4.Future<List<_i11.Attendance>>.value(
              <_i11.Attendance>[],
            ),
          )
          as _i4.Future<List<_i11.Attendance>>);

  @override
  _i4.Future<List<_i11.Attendance>> getAttendancesByStudent(int? studentId) =>
      (super.noSuchMethod(
            Invocation.method(#getAttendancesByStudent, [studentId]),
            returnValue: _i4.Future<List<_i11.Attendance>>.value(
              <_i11.Attendance>[],
            ),
          )
          as _i4.Future<List<_i11.Attendance>>);

  @override
  _i4.Future<void> bulkUpsertAttendances(
    List<_i11.Attendance>? toUpdate,
    List<_i11.Attendance>? toInsert,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#bulkUpsertAttendances, [toUpdate, toInsert]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> insertTimetableEntry(Map<String, dynamic>? entry) =>
      (super.noSuchMethod(
            Invocation.method(#insertTimetableEntry, [entry]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i12.TimetableEntry>> getTimetableEntries() =>
      (super.noSuchMethod(
            Invocation.method(#getTimetableEntries, []),
            returnValue: _i4.Future<List<_i12.TimetableEntry>>.value(
              <_i12.TimetableEntry>[],
            ),
          )
          as _i4.Future<List<_i12.TimetableEntry>>);

  @override
  _i4.Future<List<_i12.TimetableEntry>> getTimetableByClassId(int? classId) =>
      (super.noSuchMethod(
            Invocation.method(#getTimetableByClassId, [classId]),
            returnValue: _i4.Future<List<_i12.TimetableEntry>>.value(
              <_i12.TimetableEntry>[],
            ),
          )
          as _i4.Future<List<_i12.TimetableEntry>>);

  @override
  _i4.Future<List<_i12.TimetableEntry>> getTimetableEntriesByTeacher(
    int? teacherId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTimetableEntriesByTeacher, [teacherId]),
            returnValue: _i4.Future<List<_i12.TimetableEntry>>.value(
              <_i12.TimetableEntry>[],
            ),
          )
          as _i4.Future<List<_i12.TimetableEntry>>);

  @override
  _i4.Future<List<_i12.TimetableEntry>> getTimetableEntriesByClass(
    int? classId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTimetableEntriesByClass, [classId]),
            returnValue: _i4.Future<List<_i12.TimetableEntry>>.value(
              <_i12.TimetableEntry>[],
            ),
          )
          as _i4.Future<List<_i12.TimetableEntry>>);

  @override
  _i4.Future<int> updateTimetableEntry(Map<String, dynamic>? entry) =>
      (super.noSuchMethod(
            Invocation.method(#updateTimetableEntry, [entry]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteTimetableEntry(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTimetableEntry, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i12.TimetableEntry>> getTimetableEntriesByFilters({
    int? classId,
    String? dayOfWeek,
    int? teacherId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTimetableEntriesByFilters, [], {
              #classId: classId,
              #dayOfWeek: dayOfWeek,
              #teacherId: teacherId,
            }),
            returnValue: _i4.Future<List<_i12.TimetableEntry>>.value(
              <_i12.TimetableEntry>[],
            ),
          )
          as _i4.Future<List<_i12.TimetableEntry>>);

  @override
  _i4.Future<List<_i9.Subject>> getSubjectsForClass(int? classId) =>
      (super.noSuchMethod(
            Invocation.method(#getSubjectsForClass, [classId]),
            returnValue: _i4.Future<List<_i9.Subject>>.value(<_i9.Subject>[]),
          )
          as _i4.Future<List<_i9.Subject>>);

  @override
  _i4.Future<List<_i7.Teacher>> getTeachersForClass(int? classId) =>
      (super.noSuchMethod(
            Invocation.method(#getTeachersForClass, [classId]),
            returnValue: _i4.Future<List<_i7.Teacher>>.value(<_i7.Teacher>[]),
          )
          as _i4.Future<List<_i7.Teacher>>);

  @override
  _i4.Future<int> createAcademicYear(_i13.AcademicYear? academicYear) =>
      (super.noSuchMethod(
            Invocation.method(#createAcademicYear, [academicYear]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i13.AcademicYear>> getAcademicYears() =>
      (super.noSuchMethod(
            Invocation.method(#getAcademicYears, []),
            returnValue: _i4.Future<List<_i13.AcademicYear>>.value(
              <_i13.AcademicYear>[],
            ),
          )
          as _i4.Future<List<_i13.AcademicYear>>);

  @override
  _i4.Future<int> updateAcademicYear(_i13.AcademicYear? academicYear) =>
      (super.noSuchMethod(
            Invocation.method(#updateAcademicYear, [academicYear]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteAcademicYear(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAcademicYear, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> setActiveAcademicYear(_i13.AcademicYear? academicYear) =>
      (super.noSuchMethod(
            Invocation.method(#setActiveAcademicYear, [academicYear]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> createEvent(_i14.Event? event) =>
      (super.noSuchMethod(
            Invocation.method(#createEvent, [event]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i14.Event>> getEvents() =>
      (super.noSuchMethod(
            Invocation.method(#getEvents, []),
            returnValue: _i4.Future<List<_i14.Event>>.value(<_i14.Event>[]),
          )
          as _i4.Future<List<_i14.Event>>);

  @override
  _i4.Future<_i14.Event?> getEventById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEventById, [id]),
            returnValue: _i4.Future<_i14.Event?>.value(),
          )
          as _i4.Future<_i14.Event?>);

  @override
  _i4.Future<int> updateEvent(_i14.Event? event) =>
      (super.noSuchMethod(
            Invocation.method(#updateEvent, [event]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteEvent(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEvent, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i14.Event>> searchEvents(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchEvents, [query]),
            returnValue: _i4.Future<List<_i14.Event>>.value(<_i14.Event>[]),
          )
          as _i4.Future<List<_i14.Event>>);

  @override
  _i4.Future<int> createStaff(_i15.Staff? staff) =>
      (super.noSuchMethod(
            Invocation.method(#createStaff, [staff]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i15.Staff>> getStaff() =>
      (super.noSuchMethod(
            Invocation.method(#getStaff, []),
            returnValue: _i4.Future<List<_i15.Staff>>.value(<_i15.Staff>[]),
          )
          as _i4.Future<List<_i15.Staff>>);

  @override
  _i4.Future<_i15.Staff?> getStaffById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getStaffById, [id]),
            returnValue: _i4.Future<_i15.Staff?>.value(),
          )
          as _i4.Future<_i15.Staff?>);

  @override
  _i4.Future<int> updateStaff(_i15.Staff? staff) =>
      (super.noSuchMethod(
            Invocation.method(#updateStaff, [staff]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteStaff(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteStaff, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i15.Staff>> searchStaff(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchStaff, [query]),
            returnValue: _i4.Future<List<_i15.Staff>>.value(<_i15.Staff>[]),
          )
          as _i4.Future<List<_i15.Staff>>);

  @override
  _i4.Future<int> createLeave(_i16.Leave? leave) =>
      (super.noSuchMethod(
            Invocation.method(#createLeave, [leave]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i16.Leave>> getLeaves() =>
      (super.noSuchMethod(
            Invocation.method(#getLeaves, []),
            returnValue: _i4.Future<List<_i16.Leave>>.value(<_i16.Leave>[]),
          )
          as _i4.Future<List<_i16.Leave>>);

  @override
  _i4.Future<_i16.Leave?> getLeaveById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getLeaveById, [id]),
            returnValue: _i4.Future<_i16.Leave?>.value(),
          )
          as _i4.Future<_i16.Leave?>);

  @override
  _i4.Future<int> updateLeave(_i16.Leave? leave) =>
      (super.noSuchMethod(
            Invocation.method(#updateLeave, [leave]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteLeave(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLeave, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i16.Leave>> getLeavesByStaffId(int? staffId) =>
      (super.noSuchMethod(
            Invocation.method(#getLeavesByStaffId, [staffId]),
            returnValue: _i4.Future<List<_i16.Leave>>.value(<_i16.Leave>[]),
          )
          as _i4.Future<List<_i16.Leave>>);

  @override
  _i4.Future<List<_i16.Leave>> searchLeaves(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchLeaves, [query]),
            returnValue: _i4.Future<List<_i16.Leave>>.value(<_i16.Leave>[]),
          )
          as _i4.Future<List<_i16.Leave>>);

  @override
  _i4.Future<int> createPerformanceEvaluation(
    _i17.PerformanceEvaluation? evaluation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createPerformanceEvaluation, [evaluation]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i17.PerformanceEvaluation>> getPerformanceEvaluations() =>
      (super.noSuchMethod(
            Invocation.method(#getPerformanceEvaluations, []),
            returnValue: _i4.Future<List<_i17.PerformanceEvaluation>>.value(
              <_i17.PerformanceEvaluation>[],
            ),
          )
          as _i4.Future<List<_i17.PerformanceEvaluation>>);

  @override
  _i4.Future<_i17.PerformanceEvaluation?> getPerformanceEvaluationById(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPerformanceEvaluationById, [id]),
            returnValue: _i4.Future<_i17.PerformanceEvaluation?>.value(),
          )
          as _i4.Future<_i17.PerformanceEvaluation?>);

  @override
  _i4.Future<int> updatePerformanceEvaluation(
    _i17.PerformanceEvaluation? evaluation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePerformanceEvaluation, [evaluation]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deletePerformanceEvaluation(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePerformanceEvaluation, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i17.PerformanceEvaluation>>
  getPerformanceEvaluationsByStaffId(int? staffId) =>
      (super.noSuchMethod(
            Invocation.method(#getPerformanceEvaluationsByStaffId, [staffId]),
            returnValue: _i4.Future<List<_i17.PerformanceEvaluation>>.value(
              <_i17.PerformanceEvaluation>[],
            ),
          )
          as _i4.Future<List<_i17.PerformanceEvaluation>>);

  @override
  _i4.Future<List<_i17.PerformanceEvaluation>> searchPerformanceEvaluations(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchPerformanceEvaluations, [query]),
            returnValue: _i4.Future<List<_i17.PerformanceEvaluation>>.value(
              <_i17.PerformanceEvaluation>[],
            ),
          )
          as _i4.Future<List<_i17.PerformanceEvaluation>>);

  @override
  _i4.Future<int> createBorrowRecord(_i18.BorrowRecord? record) =>
      (super.noSuchMethod(
            Invocation.method(#createBorrowRecord, [record]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i18.BorrowRecord>> getBorrowRecords() =>
      (super.noSuchMethod(
            Invocation.method(#getBorrowRecords, []),
            returnValue: _i4.Future<List<_i18.BorrowRecord>>.value(
              <_i18.BorrowRecord>[],
            ),
          )
          as _i4.Future<List<_i18.BorrowRecord>>);

  @override
  _i4.Future<_i18.BorrowRecord?> getBorrowRecordById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getBorrowRecordById, [id]),
            returnValue: _i4.Future<_i18.BorrowRecord?>.value(),
          )
          as _i4.Future<_i18.BorrowRecord?>);

  @override
  _i4.Future<int> updateBorrowRecord(_i18.BorrowRecord? record) =>
      (super.noSuchMethod(
            Invocation.method(#updateBorrowRecord, [record]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteBorrowRecord(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBorrowRecord, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i18.BorrowRecord>> getBorrowRecordsByStudentId(
    int? studentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBorrowRecordsByStudentId, [studentId]),
            returnValue: _i4.Future<List<_i18.BorrowRecord>>.value(
              <_i18.BorrowRecord>[],
            ),
          )
          as _i4.Future<List<_i18.BorrowRecord>>);

  @override
  _i4.Future<List<_i18.BorrowRecord>> getBorrowRecordsByBookId(int? bookId) =>
      (super.noSuchMethod(
            Invocation.method(#getBorrowRecordsByBookId, [bookId]),
            returnValue: _i4.Future<List<_i18.BorrowRecord>>.value(
              <_i18.BorrowRecord>[],
            ),
          )
          as _i4.Future<List<_i18.BorrowRecord>>);

  @override
  _i4.Future<List<_i18.BorrowRecord>> searchBorrowRecords(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchBorrowRecords, [query]),
            returnValue: _i4.Future<List<_i18.BorrowRecord>>.value(
              <_i18.BorrowRecord>[],
            ),
          )
          as _i4.Future<List<_i18.BorrowRecord>>);

  @override
  _i4.Future<int> createBook(_i19.Book? book) =>
      (super.noSuchMethod(
            Invocation.method(#createBook, [book]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i19.Book>> getBooks() =>
      (super.noSuchMethod(
            Invocation.method(#getBooks, []),
            returnValue: _i4.Future<List<_i19.Book>>.value(<_i19.Book>[]),
          )
          as _i4.Future<List<_i19.Book>>);

  @override
  _i4.Future<_i19.Book?> getBookById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getBookById, [id]),
            returnValue: _i4.Future<_i19.Book?>.value(),
          )
          as _i4.Future<_i19.Book?>);

  @override
  _i4.Future<int> updateBook(_i19.Book? book) =>
      (super.noSuchMethod(
            Invocation.method(#updateBook, [book]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteBook(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBook, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i19.Book>> searchBooks(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchBooks, [query]),
            returnValue: _i4.Future<List<_i19.Book>>.value(<_i19.Book>[]),
          )
          as _i4.Future<List<_i19.Book>>);
}
