// Mocks generated by Mockito 5.4.6 from annotations
// in myapp/test/screens/dashboard_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter/material.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;
import 'package:myapp/attendance_model.dart' as _i15;
import 'package:myapp/class_model.dart' as _i9;
import 'package:myapp/database_helper.dart' as _i2;
import 'package:myapp/grade_model.dart' as _i18;
import 'package:myapp/providers/attendance_provider.dart' as _i14;
import 'package:myapp/providers/class_provider.dart' as _i8;
import 'package:myapp/providers/grade_provider.dart' as _i17;
import 'package:myapp/providers/student_provider.dart' as _i3;
import 'package:myapp/providers/subject_provider.dart' as _i10;
import 'package:myapp/providers/teacher_provider.dart' as _i6;
import 'package:myapp/providers/theme_provider.dart' as _i12;
import 'package:myapp/providers/timetable_provider.dart' as _i21;
import 'package:myapp/services/local_auth_service.dart' as _i19;
import 'package:myapp/student_model.dart' as _i4;
import 'package:myapp/subject_model.dart' as _i11;
import 'package:myapp/teacher_model.dart' as _i7;
import 'package:myapp/timetable_model.dart' as _i22;
import 'package:myapp/user_model.dart' as _i20;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabaseHelper_0 extends _i1.SmartFake
    implements _i2.DatabaseHelper {
  _FakeDatabaseHelper_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StudentProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockStudentProvider extends _i1.Mock implements _i3.StudentProvider {
  MockStudentProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.Student> get students =>
      (super.noSuchMethod(
            Invocation.getter(#students),
            returnValue: <_i4.Student>[],
          )
          as List<_i4.Student>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<List<_i4.Student>> fetchStudents() =>
      (super.noSuchMethod(
            Invocation.method(#fetchStudents, []),
            returnValue: _i5.Future<List<_i4.Student>>.value(<_i4.Student>[]),
          )
          as _i5.Future<List<_i4.Student>>);

  @override
  _i5.Future<void> searchStudents(String? query, {String? classId}) =>
      (super.noSuchMethod(
            Invocation.method(#searchStudents, [query], {#classId: classId}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> addStudent(_i4.Student? student) =>
      (super.noSuchMethod(
            Invocation.method(#addStudent, [student]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> updateStudent(_i4.Student? student) =>
      (super.noSuchMethod(
            Invocation.method(#updateStudent, [student]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> deleteStudent(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteStudent, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> fetchStudentsByParent(int? parentUserId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchStudentsByParent, [parentUserId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearStudents() =>
      (super.noSuchMethod(
            Invocation.method(#clearStudents, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> checkEmailUnique(String? email, [int? currentStudentId]) =>
      (super.noSuchMethod(
            Invocation.method(#checkEmailUnique, [email, currentStudentId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i4.Student?> getStudentByUserId(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getStudentByUserId, [userId]),
            returnValue: _i5.Future<_i4.Student?>.value(),
          )
          as _i5.Future<_i4.Student?>);

  @override
  void addListener(dynamic listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(dynamic listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TeacherProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockTeacherProvider extends _i1.Mock implements _i6.TeacherProvider {
  MockTeacherProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i7.Teacher> get teachers =>
      (super.noSuchMethod(
            Invocation.getter(#teachers),
            returnValue: <_i7.Teacher>[],
          )
          as List<_i7.Teacher>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> fetchTeachers() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTeachers, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addTeacher(_i7.Teacher? teacher) =>
      (super.noSuchMethod(
            Invocation.method(#addTeacher, [teacher]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateTeacher(_i7.Teacher? teacher) =>
      (super.noSuchMethod(
            Invocation.method(#updateTeacher, [teacher]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteTeacher(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTeacher, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> searchTeachers(String? name, {String? subject}) =>
      (super.noSuchMethod(
            Invocation.method(#searchTeachers, [name], {#subject: subject}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> fetchTeachersForClass(int? classId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTeachersForClass, [classId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void clearTeachers() => super.noSuchMethod(
    Invocation.method(#clearTeachers, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i7.Teacher?> getTeacherByUserId(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTeacherByUserId, [userId]),
            returnValue: _i5.Future<_i7.Teacher?>.value(),
          )
          as _i5.Future<_i7.Teacher?>);

  @override
  void addListener(dynamic listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(dynamic listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ClassProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassProvider extends _i1.Mock implements _i8.ClassProvider {
  MockClassProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i9.SchoolClass> get classes =>
      (super.noSuchMethod(
            Invocation.getter(#classes),
            returnValue: <_i9.SchoolClass>[],
          )
          as List<_i9.SchoolClass>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> fetchClasses() =>
      (super.noSuchMethod(
            Invocation.method(#fetchClasses, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> searchClasses(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchClasses, [query]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addClass(_i9.SchoolClass? schoolClass) =>
      (super.noSuchMethod(
            Invocation.method(#addClass, [schoolClass]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateClass(_i9.SchoolClass? schoolClass) =>
      (super.noSuchMethod(
            Invocation.method(#updateClass, [schoolClass]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteClass(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteClass, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i9.SchoolClass?> getClassByClassIdString(String? classId) =>
      (super.noSuchMethod(
            Invocation.method(#getClassByClassIdString, [classId]),
            returnValue: _i5.Future<_i9.SchoolClass?>.value(),
          )
          as _i5.Future<_i9.SchoolClass?>);

  @override
  void addListener(dynamic listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(dynamic listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SubjectProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubjectProvider extends _i1.Mock implements _i10.SubjectProvider {
  MockSubjectProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i11.Subject> get subjects =>
      (super.noSuchMethod(
            Invocation.getter(#subjects),
            returnValue: <_i11.Subject>[],
          )
          as List<_i11.Subject>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> fetchSubjects() =>
      (super.noSuchMethod(
            Invocation.method(#fetchSubjects, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> searchSubjects(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchSubjects, [query]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addSubject(_i11.Subject? subject) =>
      (super.noSuchMethod(
            Invocation.method(#addSubject, [subject]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateSubject(_i11.Subject? subject) =>
      (super.noSuchMethod(
            Invocation.method(#updateSubject, [subject]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteSubject(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSubject, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> fetchSubjectsForClass(int? classId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSubjectsForClass, [classId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void clearSubjects() => super.noSuchMethod(
    Invocation.method(#clearSubjects, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i11.Subject?> getSubjectById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSubjectById, [id]),
            returnValue: _i5.Future<_i11.Subject?>.value(),
          )
          as _i5.Future<_i11.Subject?>);

  @override
  void addListener(dynamic listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(dynamic listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ThemeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeProvider extends _i1.Mock implements _i12.ThemeProvider {
  MockThemeProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.ThemeMode get themeMode =>
      (super.noSuchMethod(
            Invocation.getter(#themeMode),
            returnValue: _i13.ThemeMode.system,
          )
          as _i13.ThemeMode);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void toggleTheme(bool? isDarkMode) => super.noSuchMethod(
    Invocation.method(#toggleTheme, [isDarkMode]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(dynamic listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(dynamic listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AttendanceProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAttendanceProvider extends _i1.Mock
    implements _i14.AttendanceProvider {
  MockAttendanceProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i15.Attendance> get attendances =>
      (super.noSuchMethod(
            Invocation.getter(#attendances),
            returnValue: <_i15.Attendance>[],
          )
          as List<_i15.Attendance>);

  @override
  Map<int, Map<String, int>> get studentStats =>
      (super.noSuchMethod(
            Invocation.getter(#studentStats),
            returnValue: <int, Map<String, int>>{},
          )
          as Map<int, Map<String, int>>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> fetchAttendances({
    String? date,
    int? classId,
    int? subjectId,
    int? teacherId,
    int? studentId,
    int? lessonNumber,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAttendances, [], {
              #date: date,
              #classId: classId,
              #subjectId: subjectId,
              #teacherId: teacherId,
              #studentId: studentId,
              #lessonNumber: lessonNumber,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addAttendance(_i15.Attendance? attendance) =>
      (super.noSuchMethod(
            Invocation.method(#addAttendance, [attendance]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateAttendance(_i15.Attendance? attendance) =>
      (super.noSuchMethod(
            Invocation.method(#updateAttendance, [attendance]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAttendance(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAttendance, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> fetchStudentAttendanceStats(int? studentId, int? classId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchStudentAttendanceStats, [
              studentId,
              classId,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setBulkAttendance(
    Map<String, String>? changes,
    int? classId,
    int? subjectId,
    int? teacherId,
    String? date,
    int? lessonNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setBulkAttendance, [
              changes,
              classId,
              subjectId,
              teacherId,
              date,
              lessonNumber,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  String getAttendanceStatus(int? studentId, String? date, int? lessonNumber) =>
      (super.noSuchMethod(
            Invocation.method(#getAttendanceStatus, [
              studentId,
              date,
              lessonNumber,
            ]),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.method(#getAttendanceStatus, [
                studentId,
                date,
                lessonNumber,
              ]),
            ),
          )
          as String);

  @override
  _i5.Future<List<_i15.Attendance>> getAttendancesByStudent(int? studentId) =>
      (super.noSuchMethod(
            Invocation.method(#getAttendancesByStudent, [studentId]),
            returnValue: _i5.Future<List<_i15.Attendance>>.value(
              <_i15.Attendance>[],
            ),
          )
          as _i5.Future<List<_i15.Attendance>>);

  @override
  _i5.Future<void> setAttendanceStatus(
    int? studentId,
    int? classId,
    int? subjectId,
    int? teacherId,
    String? date,
    int? lessonNumber,
    String? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setAttendanceStatus, [
              studentId,
              classId,
              subjectId,
              teacherId,
              date,
              lessonNumber,
              status,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void addListener(dynamic listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(dynamic listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GradeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockGradeProvider extends _i1.Mock implements _i17.GradeProvider {
  MockGradeProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseHelper get dbHelper =>
      (super.noSuchMethod(
            Invocation.getter(#dbHelper),
            returnValue: _FakeDatabaseHelper_0(
              this,
              Invocation.getter(#dbHelper),
            ),
          )
          as _i2.DatabaseHelper);

  @override
  List<_i18.Grade> get grades =>
      (super.noSuchMethod(
            Invocation.getter(#grades),
            returnValue: <_i18.Grade>[],
          )
          as List<_i18.Grade>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  set dbHelper(_i2.DatabaseHelper? value) => super.noSuchMethod(
    Invocation.setter(#dbHelper, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> fetchGrades() =>
      (super.noSuchMethod(
            Invocation.method(#fetchGrades, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addGrade(_i18.Grade? grade) =>
      (super.noSuchMethod(
            Invocation.method(#addGrade, [grade]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateGrade(_i18.Grade? grade) =>
      (super.noSuchMethod(
            Invocation.method(#updateGrade, [grade]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteGrade(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGrade, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i18.Grade>> getGradesByStudent(int? studentId) =>
      (super.noSuchMethod(
            Invocation.method(#getGradesByStudent, [studentId]),
            returnValue: _i5.Future<List<_i18.Grade>>.value(<_i18.Grade>[]),
          )
          as _i5.Future<List<_i18.Grade>>);

  @override
  _i5.Future<List<_i18.Grade>> getGradesByClass(int? classId) =>
      (super.noSuchMethod(
            Invocation.method(#getGradesByClass, [classId]),
            returnValue: _i5.Future<List<_i18.Grade>>.value(<_i18.Grade>[]),
          )
          as _i5.Future<List<_i18.Grade>>);

  @override
  _i5.Future<List<_i18.Grade>> getGradesBySubject(int? subjectId) =>
      (super.noSuchMethod(
            Invocation.method(#getGradesBySubject, [subjectId]),
            returnValue: _i5.Future<List<_i18.Grade>>.value(<_i18.Grade>[]),
          )
          as _i5.Future<List<_i18.Grade>>);

  @override
  _i5.Future<List<_i18.Grade>> getGradesByClassAndSubject(
    int? classId,
    int? subjectId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGradesByClassAndSubject, [
              classId,
              subjectId,
            ]),
            returnValue: _i5.Future<List<_i18.Grade>>.value(<_i18.Grade>[]),
          )
          as _i5.Future<List<_i18.Grade>>);

  @override
  _i5.Future<void> upsertGrades(List<_i18.Grade>? grades) =>
      (super.noSuchMethod(
            Invocation.method(#upsertGrades, [grades]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getAverageGradesBySubject() =>
      (super.noSuchMethod(
            Invocation.method(#getAverageGradesBySubject, []),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getAverageGradesForClass(
    int? classId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAverageGradesForClass, [classId]),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  void addListener(dynamic listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(dynamic listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [LocalAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalAuthService extends _i1.Mock implements _i19.LocalAuthService {
  MockLocalAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  bool get isSessionLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isSessionLoading),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<bool> signIn(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [username, password]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> signUp(String? username, String? password, String? role) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [username, password, role]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void signOut() => super.noSuchMethod(
    Invocation.method(#signOut, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<List<_i20.User>> getUsersByRole(String? role) =>
      (super.noSuchMethod(
            Invocation.method(#getUsersByRole, [role]),
            returnValue: _i5.Future<List<_i20.User>>.value(<_i20.User>[]),
          )
          as _i5.Future<List<_i20.User>>);

  @override
  void addListener(dynamic listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(dynamic listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TimetableProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimetableProvider extends _i1.Mock implements _i21.TimetableProvider {
  MockTimetableProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i22.TimetableEntry> get timetableEntries =>
      (super.noSuchMethod(
            Invocation.getter(#timetableEntries),
            returnValue: <_i22.TimetableEntry>[],
          )
          as List<_i22.TimetableEntry>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> fetchTimetableEntries() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTimetableEntries, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i22.TimetableEntry>> getTimetableByClassId(int? classId) =>
      (super.noSuchMethod(
            Invocation.method(#getTimetableByClassId, [classId]),
            returnValue: _i5.Future<List<_i22.TimetableEntry>>.value(
              <_i22.TimetableEntry>[],
            ),
          )
          as _i5.Future<List<_i22.TimetableEntry>>);

  @override
  _i5.Future<void> fetchTimetableEntriesByClass(int? classId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTimetableEntriesByClass, [classId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> fetchTimetableEntriesByTeacher(int? teacherId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTimetableEntriesByTeacher, [teacherId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addTimetableEntry(_i22.TimetableEntry? entry) =>
      (super.noSuchMethod(
            Invocation.method(#addTimetableEntry, [entry]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateTimetableEntry(_i22.TimetableEntry? entry) =>
      (super.noSuchMethod(
            Invocation.method(#updateTimetableEntry, [entry]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteTimetableEntry(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTimetableEntry, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void addListener(dynamic listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(dynamic listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
